### ISSUE TITLE
Muon Analysis fitted curve has same colour as raw data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30526]
**Original reporter:** James Lorde

### Expected behavior
The fitted line should be plotted in a different colour to the raw data.

### Actual behavior
The fitting line is plotted with the same colour as the raw data, making it difficult to see.

### Steps to reproduce the behavior
1. Muon Analysis interface
2. HIFI instrument. Load runs 175833-43
3. Go to Fitting tab
4. Add functions `Linear Background` and `ExpDecayOsc`
6. Click `Fit`. It does the fit but the fitted data is plotted in the same colour.

### Platforms affected
Found on windows

**Comment by AnthonyLim23** [comment]
I think this is fixed

**Comment by Matt-Cumber** [comment]
Re-opening this issue as it still exists and can be reliably reproduce. Loading EMU20883-93 and doing a fit causes the fit line to be the same colour as well as MUSR62260-62. Looks to be related to there being more than 10 plotted lines at once resulting in the colour queue to be reset

**Comment by martyngigg** [comment]
Fixed by #31389
